Initial pr
KseniyaMikhailiuk/Cinema-ticket-reservation-system pull request #1
Opened 2018-12-11 06:23 UTC by KseniyaMikhailiuk

2018-12-11 06:57 UTC, AndreiShenets requested changes

2018-12-11 06:57 UTC, AndreiShenets commented on front/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
Where is PUBLIC_URL taken from? Will it be filled when you publish your site in production mode?

2018-12-11 06:57 UTC, AndreiShenets commented on front/public/index.html
> +    <link rel="stylesheet" href="<NODE_MODULES_FOLDER>/react-responsive-carousel/lib/styles/carousel.min.css"/>
Where is PUBLIC_URL taken from? Will it be filled when you publish your site in production mode?

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/Common/Footer/index.js
> +const Footer = () =>{
Please write down a task for a future: add eslint to the project. Why? To help yourself and fix code style issues. Space should be placed between => and {

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/Common/Header/index.js
> +                <li><NavLink to="./Home" activeClassName="selected">Главная</NavLink></li>
Russian language here but english in other places. Please choose one or think about adding localization. We add localization in any case in future

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/FilmListItem/index.js
> +    cityFilter = "Минск"
Why are you sure that such city exists?

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/FilmListItem/cinemaSeanceInfo.js
> +    console.log(filmInfo);
There shouldn't be any console.log in master branch (only in some rare cases, I doubt it is such case)

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/FilmListItem/cinemaSeanceInfo.js
> +                        {seance.getHours() + ':' + seance.getMinutes()}
Prefer to use string interpolation

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/FilmListItem/index.js
> +                        <CinemaSeanceInfo filmInfo={itemInfo}/>
One indend should be always added for content. Also such filtering is worth to add outside of jsx markup. Also I **strongly** recommend to use followin style for chaining:

```
    itemInfo
        .cities
        .find(city => city.name === cityFilter)
        .cinemas
        .map(itemInfo => 
            <CinemaSeanceInfo filmInfo={itemInfo}/>  
        )
```
The reason is for better reading. My recommendations with explanations for code style here https://github.com/AndreiShenets/code-styles

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/FilterPanel/index.js
> +for(var i = 0; i < 9; i++){
Magic numbers!!!
Why did you decide to use 10 dates? Am I right that it is filter dates? It is worth to use services for such cases. Also you have to be sure that such solution is handy for end user

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/OrderSection/filmInfo.js
> +                <p>25-05-2048</p> {/*{filmInfo.date}*/}
Let's discuss how to implement frontend without backend

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/OrderSection/hallPlan.js
> +                                if(seat.type === "loveseat"){
Magic string!!!

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/components/SignInForm/authorizationForm.js
> +                    <label htmlFor="rememberMe">Запомнить меня?</label>
What do you need remember me for?

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/services/api/filmsDB.js
> +                            new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 20),
Function for generation of such values

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/services/api/filmsDB.js
> +export const fetchFilmList = (filter) => {
Promise should be used

2018-12-11 06:57 UTC, AndreiShenets commented on front/src/store/actions/index.js
> +export const fetchFilmList = (filter = new Date()) => ({
Are you sure that date is only parameter for filter? How do you think this is going to work with server?

2018-12-11 09:48 UTC, AndreiShenets commented on front/src/components/FilmListItem/cinemaSeanceInfo.js
> +                        {seance.getHours() + ':' + seance.getMinutes()}
momentjs

2018-12-11 09:53 UTC, AndreiShenets commented on front/src/components/FilterPanel/index.js
> +for(var i = 0; i < 9; i++){
Datepicker

2018-12-18 07:47 UTC, ghost requested changes

2018-12-18 07:47 UTC, andrei-shenets-simpligov commented on front/src/components/FilterPanel/index.js
> +                    placeholder={filter.city}
Value not placeholder

2018-12-18 07:47 UTC, andrei-shenets-simpligov commented on front/src/App.js
> +                        <Route path='/TicketOrder/:film/:city/:cinema/:hall/:time' component={TicketOrder}/>
Route? sessionId

2018-12-18 07:47 UTC, andrei-shenets-simpligov commented on front/src/services/api/filmsFetch.js
>  export const fetchFilmInfo = (filmName) =>
Cannot get film by name in case of two different films with the same name

2018-12-18 07:47 UTC, andrei-shenets-simpligov commented on front/src/services/api/hallPlanFetch.js
> +    delay(500)
```
delay(500)
    .then(() => {
        let selectedSeat = {};
     
        cinemaHallPlans
            .find(city => city.cityName === seatInfo.selectedSeanceInfo.city)
            .cinemas
            .find(cinema => cinema.name === seatInfo.selectedSeanceInfo.cinema)
            .halls
            .find(hall => hall.number === seatInfo.selectedSeanceInfo.hall)
            .plan
            .forEach(line => {
                line.forEach(seat => {
                    if (seat.id === seatInfo.seatId) {
                        seat.occupied = true;
                        selectedSeat = seat;
                    }
                })
            })

        return selectedSeat;
    }) 
```

2018-12-18 09:49 UTC, AndreiShenets approved these changes

2018-12-18 09:49 UTC, merged